### PR TITLE
Reorganization, attempt to fix C++ file-server

### PR DESCRIPTION
**Pull request by nicovank**
This re-organizes files to match the structure of https://github.com/nicovank/Energy-Languages. This allows to just re-use all scripts as-is without any changes which is convenient.

`sort` and `sudoku` seem to work for all languages, `graph` for all but Python which I think is the current state of things.

I've also tried to fix `file-server`, with not much luck yet.

@dungwinux Can you please take a quick look at this to make sure I didn't miss or break anything?

### CODE REVIEW

**Comment by dungwinux** [comment]
I will look into it tonight and hopefully fix the issue

**Comment by dungwinux** [comment]
- `file-server` works fine for both C++ and Python
- Python `graph` also works fine, just slow
  > real    2m43.452s
  > user    2m40.506s
  > sys     0m2.841s
- Go and Java Makefile remain unchanged. You can cherry picks changes for benchmarking from `energy-measure-patch`

**Comment by nicovank** [comment]
> file-server works fine for both C++ and Python

Really? IIRC it was not working for me in C++ (it would just hang / time out). Did you change anything?

**Comment by dungwinux** [comment]
No, I cloned on fresh Ubuntu 22.04 install. I do run the server first, then the client. The server will stay even after the client finish requesting files.

**Pull request merged**
